### ISSUE TITLE
Wrong key when Extractor from widevineclient3

### ISSUE THREAD

**Issue by khangnh** [WHTJEON/widevineclient3#2]
I tried get with -pssh but the result returned the wrong key compared to when I used l3 decryptor. Let me know where the problem lies. I tried to get with Bitmovin gave correct results, but only true for Bitmovin and other sites all gave wrong results.

-pssh AAAAR3Bzc2gAAAAA7e+LqXnWSs6jyCfc1R0h7QAAACcIARIQYRm96sFvguti6GFvcv9HcxoDdHZiIgxORGd4TlRreE9Td3c=

![Screenshot 2021-05-06 181940](https://user-images.githubusercontent.com/50206148/117290268-ca2a5a00-ae97-11eb-8c5b-6f7fc965d217.png)

Key correct is 626e16c21dd9f24afaea4330ad9a4c22

**Comment by S-hdyn** [comment]
Hi, how to run wvclient.py?

**Comment by WHTJEON** [comment]
That's because you didn't provide the right license_url. You should add -url (License URL)

**Comment by kimo1000000** [comment]
i find this error any solutions please
![error2](https://user-images.githubusercontent.com/56774859/118556870-af43c980-b764-11eb-90c8-ca80119804a6.jpg)

**Comment by WHTJEON** [comment]
> i find this error any solutions please
> ![error2](https://user-images.githubusercontent.com/56774859/118556870-af43c980-b764-11eb-90c8-ca80119804a6.jpg)

```
$ pip install protobuf
```
